version: "3.3"

services:
  app:
    build: .
    environment:
      DB_URL: "mongodb://db:27017"
    depends_on:
      - "db"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules

  db:
    image: bitnami/mongodb:5.0.5
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

volumes:
  mongodb_data:
    driver: local