version: "3.8"

services:
  app:
    image: node:lts-bullseye
    environment:
      DB_URL: "mongbodb"
    depends_on:
      - "db"
  db:
    image: bitnami/mongodb:5.0.5
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

volumes:
  mongodb_data:
    driver: local